import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from 'react-hot-toast'
import { ThemeProvider } from "@/providers/theme-provider";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: "swap",
})
export const metadata: Metadata = {
  title: "Zahra Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={cn('antialiased', poppins.className)} suppressHydrationWarning={true}
      >
        <ThemeProvider attribute={'class'} enableSystem defaultTheme="light">
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
